ALTER TABLE "AboutContent" ADD COLUMN "subtitle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ContactContent" ADD COLUMN "socialLinks" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Project" ADD COLUMN "techStack" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Project" ADD COLUMN "liveUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "sourceUrl" TEXT NOT NULL DEFAULT '';
